version: '3.7'

services:

  web:
    image: "johnnyms/testing:latest"
    build:
       context: .
       dockerfile: ./Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3001:80
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30